apiVersion: v1
kind: Namespace
metadata:
    name: fabrick8s

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orgorderer1-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/share/crypto-config/ordererOrganizations/orgorderer1
    server: 10.0.0.14

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: fabrick8s
 name: orgorderer1-pv
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Mi

---
